services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: sst-core
    env_file:
      - .env.core
    volumes:
      - ./.env.core:/app/.env:ro
      - ./core/src/core:/app/src/core:ro
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - PYTHONPATH=/app/src
      - PREFECT_API_URL=http://prefect.outergods.lan/api
    extra_hosts:
      - "prefect.outergods.lan:192.168.11.205"
      - "swfs-s3.outergods.lan:192.168.11.205"

networks:
  default:
    name: sst-network
    external: true
