services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: sst-worker
    env_file:
      - .env.worker
    volumes:
      - ./.env.worker:/app/.env:ro
    environment:
      - PYTHONPATH=/app/src:/app/src/worker
      - TZ=${TZ:-Asia/Tokyo}
      - PREFECT_API_URL=http://prefect.outergods.lan/api
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "prefect.outergods.lan:192.168.11.205"
      - "swfs-s3.outergods.lan:192.168.11.205"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    command: ["uv", "run", "src/worker/main.py"]
    restart: always

networks:
  default:
    name: sst-network
    external: true
